import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  makeCodeSidebar: [{type: 'autogenerated', dirName: 'MakeCode-Projects'}],
  eduBlocksSidebar: [{type: 'autogenerated', dirName: 'EduBlocks-Projects'}],
  pythonSidebar: [{type: 'autogenerated', dirName: 'Python-Projects'}],
  
   
};

/* export default 
  MakeCode: {
    'Shake, Code & Battle: micro:bit Rock Paper Scissors': ['MakeCode-Projects/Rock-Paper-Scissors/Overview',
      'MakeCode-Projects/Rock-Paper-Scissors/Set-Up',
      'MakeCode-Projects/Rock-Paper-Scissors/Coding',
      'MakeCode-Projects/Rock-Paper-Scissors/DownloadingTheCode',
      'MakeCode-Projects/Rock-Paper-Scissors/HowToPlay',
      { 
        type: 'link',
        label: 'PDF Download', // The link label
        href: 'https://go.raspikidd.com/MCRPS', // The external URL
      },],
      
    'Micro:fit - Your DIY Step Counter': ['MakeCode-Projects/FitBit-Clone/Overview', 
      'MakeCode-Projects/FitBit-Clone/Set-Up',
      'MakeCode-Projects/FitBit-Clone/Coding',
      'MakeCode-Projects/FitBit-Clone/DownloadingTheCode',
      'MakeCode-Projects/FitBit-Clone/HowToPlay',
      {
        type: 'link',
        label: 'PDF Download', // The link label
        href: 'https://go.raspikidd.com/MCSC', // The external URL
      },],
      'Mission: Environment Detective - Exploring Our World with micro:bit': ['MakeCode-Projects/Sensing-the-Environment/Overview', 
      'MakeCode-Projects/Sensing-the-Environment/Set-Up',
      'MakeCode-Projects/Sensing-the-Environment/Coding',
      'MakeCode-Projects/Sensing-the-Environment/DownloadingTheCode',
      'MakeCode-Projects/Sensing-the-Environment/HowToPlay',
      {
        type: 'link',
        label: 'PDF Download', // The link label
        href: 'https://go.raspikidd.com/MCES', // The external URL
      },],
      'Signal Builder: DIY micro:bit Traffic Lights': ['MakeCode-Projects/DIY-Traffic-Lights/Overview', 
      'MakeCode-Projects/DIY-Traffic-Lights/Creating-the-circuit',
      'MakeCode-Projects/DIY-Traffic-Lights/Set-Up',
      'MakeCode-Projects/DIY-Traffic-Lights/Coding',
      'MakeCode-Projects/DIY-Traffic-Lights/DownloadingTheCode',
      'MakeCode-Projects/DIY-Traffic-Lights/HowToPlay',
      {
        type: 'link',
        label: 'PDF Download', // The link label
        href: 'https://go.raspikidd.com/MCTL', // The external URL
      },],
      'Spooky Signals: micro:bit Ghost Throwing Challenge': ['MakeCode-Projects/Spooky-Signals/Overview', 
      'MakeCode-Projects/Spooky-Signals/Set-Up',
      'MakeCode-Projects/Spooky-Signals/Coding',
      'MakeCode-Projects/Spooky-Signals/DownloadingTheCode',
      'MakeCode-Projects/Spooky-Signals/HowToPlay',
      {
        type: 'link',
        label: 'PDF Download', // The link label
        href: 'https://go.raspikidd.com/MCSS', // The external URL
      },],
  },
  EduBlocks: {
    'Shake, Code & Battle: micro:bit Rock Paper Scissors': ['EduBlocks-Projects/Rock-Paper-Scissors/Overview',
      'EduBlocks-Projects/Rock-Paper-Scissors/Set-Up',
      'EduBlocks-Projects/Rock-Paper-Scissors/Coding',
      'EduBlocks-Projects/Rock-Paper-Scissors/DownloadingTheCode',
      'EduBlocks-Projects/Rock-Paper-Scissors/HowToPlay',
      {
        type: 'link',
        label: 'PDF Download', // The link label
        href: 'https://go.raspikidd.com/EBRPS', // The external URL
      },],
      'Micro:fit - Your DIY Step Counter': ['EduBlocks-Projects/FitBit-Clone/Overview',
      'EduBlocks-Projects/FitBit-Clone/Set-Up',
      'EduBlocks-Projects/FitBit-Clone/Coding',
      'EduBlocks-Projects/FitBit-Clone/DownloadingTheCode',
      'EduBlocks-Projects/FitBit-Clone/HowToPlay',
      {
        type: 'link',
        label: 'PDF Download', // The link label
        href: 'https://go.raspikidd.com/EBSC', // The external URL
      },],
      'Mission: Environment Detective - Exploring Our World with micro:bit': ['EduBlocks-Projects/Sensing-the-Environment/Overview',
      'EduBlocks-Projects/Sensing-the-Environment/Set-Up',
      'EduBlocks-Projects/Sensing-the-Environment/Coding',
      'EduBlocks-Projects/Sensing-the-Environment/DownloadingTheCode',
      'EduBlocks-Projects/Sensing-the-Environment/HowToPlay',
      {
        type: 'link',
        label: 'PDF Download', // The link label
        href: 'https://go.raspikidd.com/EBES', // The external URL
      },],
      'Signal Builder: DIY micro:bit Traffic Lights': ['EduBlocks-Projects/DIY-Traffic-Lights/Overview', 
      'EduBlocks-Projects/DIY-Traffic-Lights/Creating-the-circuit',
      'EduBlocks-Projects/DIY-Traffic-Lights/Set-Up',
      'EduBlocks-Projects/DIY-Traffic-Lights/Coding',
      'EduBlocks-Projects/DIY-Traffic-Lights/DownloadingTheCode',
      'EduBlocks-Projects/DIY-Traffic-Lights/HowToPlay',
      {
        type: 'link',
        label: 'PDF Download', // The link label
        href: 'https://go.raspikidd.com/EBTL', // The external URL
      },],
      'Spooky Signals: Ghost Throwing Challenge': ['EduBlocks-Projects/Spooky-Signals/Overview', 
      'EduBlocks-Projects/Spooky-Signals/Set-Up',
      'EduBlocks-Projects/Spooky-Signals/Coding',
      'EduBlocks-Projects/Spooky-Signals/DownloadingTheCode',
      'EduBlocks-Projects/Spooky-Signals/HowToPlay',
      {
        type: 'link',
        label: 'PDF Download', // The link label
        href: 'https://go.raspikidd.com/EBSS', // The external URL
      },],
  },
  Python: {
    'Shake, Code & Battle: micro:bit Rock Paper Scissors': ['Python-Projects/Rock-Paper-Scissors/Overview',
      'Python-Projects/Rock-Paper-Scissors/Set-Up',
      'Python-Projects/Rock-Paper-Scissors/Coding',
      'Python-Projects/Rock-Paper-Scissors/DownloadingTheCode',
      'Python-Projects/Rock-Paper-Scissors/HowToPlay',
      {
        type: 'link',
        label: 'PDF Download', // The link label
        href: 'https://go.raspikidd.com/PYRPS', // The external URL
      },],
    
    'Micro:fit - Your DIY Step Counter': ['Python-Projects/FitBit-Clone/Overview',
      'Python-Projects/FitBit-Clone/Set-Up',
      'Python-Projects/FitBit-Clone/Coding',
      'Python-Projects/FitBit-Clone/DownloadingTheCode',
      'Python-Projects/FitBit-Clone/HowToPlay',
      {
        type: 'link',
        label: 'PDF Download', // The link label
        href: 'https://go.raspikidd.com/PYSC', // The external URL
      },],

      'Mission: Environment Detective - Exploring Our World with micro:bit': ['Python-Projects/Sensing-the-Environment/Overview',
      'Python-Projects/Sensing-the-Environment/Set-Up',
      'Python-Projects/Sensing-the-Environment/Coding',
      'Python-Projects/Sensing-the-Environment/DownloadingTheCode',
      'Python-Projects/Sensing-the-Environment/HowToPlay',
      {
        type: 'link',
        label: 'PDF Download', // The link label
        href: 'https://go.raspikidd.com/PYES', // The external URL
      },],
      'Signal Builder: DIY micro:bit Traffic Lights': ['Python-Projects/DIY-Traffic-Lights/Overview', 
      'Python-Projects/DIY-Traffic-Lights/Creating-the-circuit',
      'Python-Projects/DIY-Traffic-Lights/Set-Up',
      'Python-Projects/DIY-Traffic-Lights/Coding',
      'Python-Projects/DIY-Traffic-Lights/DownloadingTheCode',
      'Python-Projects/DIY-Traffic-Lights/HowToPlay',
      {
        type: 'link',
        label: 'PDF Download', // The link label
        href: 'https://go.raspikidd.com/PYTL', // The external URL
      },],
      'Spooky Signals: micro:bit Ghost Throwing Challenge': ['Python-Projects/Spooky-Signals/Overview', 
        'Python-Projects/Spooky-Signals/Set-Up',
        'Python-Projects/Spooky-Signals/Coding',
        'Python-Projects/Spooky-Signals/DownloadingTheCode',
        'Python-Projects/Spooky-Signals/HowToPlay',
        {
          type: 'link',
          label: 'PDF Download', // The link label
          href: 'https://go.raspikidd.com/PYSS', // The external URL
        },],
  },
}; */
export default sidebars;
