import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
/*const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    //'intro',
    //'hello',
    {
      type: 'category',
      label: 'MakeCode Projects',
      items: ['MakeCode-Projects/Rock-Paper-Scissors/Overview',
        'MakeCode-Projects/Rock-Paper-Scissors/Set-Up',
        'MakeCode-Projects/Rock-Paper-Scissors/Coding',
        'MakeCode-Projects/Rock-Paper-Scissors/DownloadingTheCode',
        'MakeCode-Projects/Rock-Paper-Scissors/HowToPlay'
      ],
    },
    {
      type: 'category',
      label: 'EduBlocks Projects',
      items: ['EduBlocks-Projects/Rock-Paper-Scissors/Overview',
        'EduBlocks-Projects/Rock-Paper-Scissors/Set-Up',
        'EduBlocks-Projects/Rock-Paper-Scissors/Coding',
        'EduBlocks-Projects/Rock-Paper-Scissors/DownloadingTheCode',
        'EduBlocks-Projects/Rock-Paper-Scissors/HowToPlay'
      ],
    },
    {
      type: 'category',
      label: 'Python Projects',
      items: ['Python-Projects/Rock-Paper-Scissors/Overview',
        'Python-Projects/Rock-Paper-Scissors/Set-Up',
        'Python-Projects/Rock-Paper-Scissors/Coding',
        'Python-Projects/Rock-Paper-Scissors/DownloadingTheCode',
        'Python-Projects/Rock-Paper-Scissors/HowToPlay'
      ],
    },
  ],
  
   
};*/

export default {
  MakeCode: {
    'Rock Paper Scissors': ['MakeCode-Projects/Rock-Paper-Scissors/Overview',
      'MakeCode-Projects/Rock-Paper-Scissors/Set-Up',
      'MakeCode-Projects/Rock-Paper-Scissors/Coding',
      'MakeCode-Projects/Rock-Paper-Scissors/DownloadingTheCode',
      'MakeCode-Projects/Rock-Paper-Scissors/HowToPlay',
      {
        type: 'link',
        label: 'PDF Download', // The link label
        href: 'https://go.raspikidd.com/MCRPS', // The external URL
      },],
      
    'FitBit Clone Project': ['MakeCode-Projects/FitBit-Clone/Overview']
  },
  EduBlocks: {
    'Rock Paper Scissors': ['EduBlocks-Projects/Rock-Paper-Scissors/Overview',
      'EduBlocks-Projects/Rock-Paper-Scissors/Set-Up',
      'EduBlocks-Projects/Rock-Paper-Scissors/Coding',
      'EduBlocks-Projects/Rock-Paper-Scissors/DownloadingTheCode',
      'EduBlocks-Projects/Rock-Paper-Scissors/HowToPlay',
      {
        type: 'link',
        label: 'PDF Download', // The link label
        href: 'https://go.raspikidd.com/EBRPS', // The external URL
      },],
  },
  Python: {
    'Rock Paper Scissors': ['Python-Projects/Rock-Paper-Scissors/Overview',
      'Python-Projects/Rock-Paper-Scissors/Set-Up',
      'Python-Projects/Rock-Paper-Scissors/Coding',
      'Python-Projects/Rock-Paper-Scissors/DownloadingTheCode',
      'Python-Projects/Rock-Paper-Scissors/HowToPlay',
      {
        type: 'link',
        label: 'PDF Download', // The link label
        href: 'https://go.raspikidd.com/PYRPS', // The external URL
      },],
  },
};
//export default sidebars;
